name: CI and Python application tests with Github Actions

on: 
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        make install

    - name: Lint code
      run: |
        make lint
        
    - name: Run tests
      run: |
        make test
         
    - name: Format code
      run: |
        make format
      
    - name: Build container
      run: |
        make build

    - name: Run container
      run: |
        make run
         
    - name: Deploy
      run: |
        make deploy
